[package]
name = "serv"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.1"
serde = "1.0.216"
toml = "0.8.19"
tokio = "1.42.0"
chrono = "0.4.39"
tokio-cron-scheduler = "0.13.0"
hex = "0.4.3"
api = { version = "0.1.0", path = "../api" }